### ISSUE TITLE
Notify users that the monthly report has been successfully submitted

### ISSUE THREAD

**Issue by gretacv** [Vizzuality/vizz_trackr#21]
At the moment I think the only two ways to be sure the report has been successfully submitted is via not finding the `estimated` checkbox or because in the reports summary the row is not yellow anymore. I think a more straightforward way is necessary. For example an email, a slack integration or just a note in the interface somehow.

**Comment by CV-Gate** [comment]
I'd vote for being not being too noisy, and I think that showing a message on the interface may work for that.

**Comment by gretacv** [comment]
I was looking the reports page (http://vizz-trackr.herokuapp.com/users/19/reports?reporting_period_id=11&commit=Filter) and I have thought that maybe a legend indicating that yellow means the report hasn't been submitted could do the trick.

**Comment by gretacv** [comment]
This has been implemented right?
