### ISSUE TITLE
Suggestion: In reporting period page show a visual summary

### ISSUE THREAD

**Issue by gretacv** [Vizzuality/vizz_trackr#32]
I think it could be cool to have a network graph of how the members have been involved in the same projects.
@01painadam might have great code for this

**Comment by simaob** [comment]
If you sketch something up we can add to the ToDo list. I really want to improve many of our screens, and make the information architecture better as well as showing the best possible data. We might need some new pages.

**Comment by gretacv** [comment]
This is something I did from the November report. It lacks any designers or dev love, maybe something better can be done. 

![VizzNet_month_key9](https://user-images.githubusercontent.com/11423895/72264829-aa748000-361b-11ea-9e3a-76c1fa665395.png)
