### ISSUE TITLE
Average Projects per Reporter

### ISSUE THREAD

**Issue by gretacv** [Vizzuality/vizz_trackr#33]
I am not sure what: `Average Projects per Reporter` refers to. Is it the average proportion of how much each person dedicates to a single project? I think this needs to be clarified. If it is a proportion it might be easier to read in percentage.
Also maybe it is cool to know the average of how many projects each person was that month. Then it might be possible to see within each functional team to see if there are people with a large amount of projects (e.g. above the average, median) and double check that the person is not having too many projects (this was something mentioned in a Rosling retro).

**Comment by simaob** [comment]
This average is the number of projects that on average each person reports too. So some people might report 1, others 3, the average would be 2. It needs some work and thinking into proper metrics that give info :D
