### ISSUE TITLE
It is possible to submit a report with more than 100% reported

### ISSUE THREAD

**Issue by gretacv** [Vizzuality/vizz_trackr#34]
Hi. By mistake I pressed enter and my report was submitted before I finished fill it out. The total of time reported was 103% and it was possible to submit it. I think it might be useful to raise an error in these cases and not make it possible to submit the report.

**Comment by simaob** [comment]
I am still not 100% sure about this. If people did extra time, should we capture it here?

**Comment by gretacv** [comment]
That's a good point. To my understanding we want to avoid people working more hours than they should.  Would it therefore make sense to have a message saying "you have reported more than 100%". Does this make sense?
