### ISSUE TITLE
chart for project burn should plot data irrespective of set start/end dates

### ISSUE THREAD

**Issue by hotzevzl** [Vizzuality/vizz_trackr#44]
![Screenshot_2020-02-19 VizzTrackr - Contract - Open Timber Portal - Live](https://user-images.githubusercontent.com/47385021/74866560-fddc9b00-534a-11ea-8e6f-bca1e1692800.png)

In the screenshot above, data is plotted only up to 31 July 2019, which is the date set as **End date** for the project, although cost data is available up to February 2020 (including projection) for this project, and this is taken into account correctly for the **Cost to date** and **Costs with projection**.

**Comment by simaob** [comment]
Thanks for reporting. Fixed and deploying to prod!
