### ISSUE TITLE
in Firefox, x axis of Project burn chart displays months (mostly) out of order

### ISSUE THREAD

**Issue by hotzevzl** [Vizzuality/vizz_trackr#45]
![Screenshot_2020-02-19 VizzTrackr - Contract - Open Timber Portal - Live](https://user-images.githubusercontent.com/47385021/74866863-7ba0a680-534b-11ea-8a1c-b8232e00d9ee.png)

See screenshot above.

At first sight and inferring a pattern from a single specific case :scream:, months with data are sorted correctly and displayed first, following by the months without data sorted correctly.

**Comment by simaob** [comment]
Fixed in https://github.com/Vizzuality/vizz_trackr/commit/3d2efdbd1de575e17c627c6f04d89870b7527e19, and https://github.com/Vizzuality/vizz_trackr/commit/63c552b6a49f482c02089652e36a7e71ddcef14c . Deployed to production.
