### ISSUE TITLE
dropdown in reporting_periods/22/reports doesn't work

### ISSUE THREAD

**Issue by gretacv** [Vizzuality/vizz_trackr#64]
It is not possible to filter the table by role. it directs to reporting_periods/22?role_id=4 and I think it should redirect to roles/4
![image](https://user-images.githubusercontent.com/11423895/78504562-61d9e800-776e-11ea-90bc-efaa143e72eb.png)

**Comment by simaob** [comment]
Ooops, forgot to update the URL when I changed this page. =) Fixed and deploying. Thanks for reporting!
