### ISSUE TITLE
Reporting periods are not summing up %s on CSV file

### ISSUE THREAD

**Issue by suromao** [Vizzuality/vizz_trackr#78]
Laura realized that when she downloaded the reports from May, the CSV file was only presenting the %s for each person on their regular FA, i.e., if the same person reported 2 different FAs it only appears one. On VT is sums up to 100% correctly.

**Comment by simaob** [comment]
For the download we can sum the total per person and project, right? No need to have the breakdown per FA?

**Comment by suromao** [comment]
No, for accounting purposes no need to have the breakdown. Just the total per person.

**Comment by simaob** [comment]
Fixed by this https://github.com/Vizzuality/vizz_trackr/commit/279582a7f53907dc0d040be7cbe9da4f443a44ea . deploy underway.
